language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then composer require php-coveralls/php-coveralls; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then composer require --dev vimeo/psalm; fi

script:
  - tools/check-syntax.sh
  - ant
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then vendor/bin/psalm; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then php vendor/bin/php-coveralls -v; fi
